import { chromium } from 'playwright-core'
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } })
const errs = []
page.on('pageerror', (e) => errs.push(String(e).slice(0, 300)))
page.on('console', (m) => { if (m.type() === 'error') errs.push('console: ' + m.text().slice(0, 200)) })
await page.goto('http://127.0.0.1:3100', { waitUntil: 'domcontentloaded' })
await page.waitForSelector('[data-mm-shell="v3"]', { timeout: 25000 })
await page.click('[data-mm-navlist] div[role="tab"]:has-text("比赛工作台")')
await page.waitForTimeout(1500)
const sel = page.locator('select').first()
const value = await sel.evaluate((el) => { const o = [...el.options].find((o) => o.textContent.includes('overnight-e2e')); return o ? o.value : '' })
await sel.selectOption(value)
await page.waitForTimeout(1200)
await page.click('button:has-text("实验")')
await page.waitForTimeout(400)
await page.click('button:has-text("执行实验")')
await page.waitForTimeout(8000)
const text = await page.evaluate(() => document.querySelector('[data-mm-main]').innerText.slice(0, 900))
console.log('ERRORS:', JSON.stringify(errs))
console.log('---MAIN TEXT---')
console.log(text)
await page.screenshot({ path: 'REVIEW/overnight/lab-debug.png' })
await browser.close()
