import { chromium } from 'playwright-core'
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } })
const errs = []
page.on('pageerror', (e) => errs.push(String(e).slice(0, 200)))
await page.goto('http://127.0.0.1:3100', { waitUntil: 'domcontentloaded' })
await page.waitForSelector('[data-mm-shell="v3"]', { timeout: 25000 })
await page.click('[data-mm-navlist] div[role="tab"]:has-text("文献研究")')
await page.waitForTimeout(600)
await page.fill('input[placeholder*="heliostat"]', 'heliostat field layout optimization solar thermal power')
await page.fill('input[type="date"]', '2023-09-07')
await page.click('button:has-text("研究相关文献")')
await page.waitForFunction(() => document.body.innerText.includes('截止模式'), { timeout: 90000 })
await page.waitForTimeout(800)
await page.screenshot({ path: 'REVIEW/overnight/literature.png' })
const txt = await page.evaluate(() => document.querySelector('[data-mm-section="literature"]').innerText.slice(0, 400))
console.log('ERRORS:', errs.length)
console.log(txt)
await browser.close()
